services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: sector-server
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@sector-platform-pg-sksf8e:5432/sector
      - NODE_ENV=production
    networks:
      - sector-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: sector-web
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - server
    networks:
      - sector-network

networks:
  sector-network:
    driver: bridge
